/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

/* ============================================================
 * RCC
 * ============================================================ */

#define RCC_AHB1ENR    (*(volatile uint32_t *)0x40023830U)
#define RCC_APB1ENR    (*(volatile uint32_t *)0x40023840U)

/* ============================================================
 * GPIOA
 * ============================================================ */

#define GPIOA_MODER    (*(volatile uint32_t *)0x40020000U)
#define GPIOA_AFRL     (*(volatile uint32_t *)0x40020020U)
#define GPIOA_BSRR     (*(volatile uint32_t *)0x40020018U)

/* ============================================================
 * USART2
 * ============================================================ */

#define USART2_SR      (*(volatile uint32_t *)0x40004400U)
#define USART2_DR      (*(volatile uint32_t *)0x40004404U)
#define USART2_BRR     (*(volatile uint32_t *)0x40004408U)
#define USART2_CR1     (*(volatile uint32_t *)0x4000440CU)

/* ============================================================
 * NVIC
 * ============================================================ */

#define NVIC_ISER1     (*(volatile uint32_t *)0xE000E104U)

/* ============================================================
 * Біти USART2
 * ============================================================ */

#define USART_SR_RXNE      (1U << 5)
#define USART_SR_TXE       (1U << 7)

#define USART_CR1_RE       (1U << 2)
#define USART_CR1_TE       (1U << 3)
#define USART_CR1_RXNEIE   (1U << 5)
#define USART_CR1_UE       (1U << 13)

/* ============================================================
 * Кільцевий буфер
 * Розмір має бути степенем числа 2: 8, 16, 32, 64...
 * ============================================================ */

#define RX_BUFFER_SIZE     32U
#define RX_BUFFER_MASK     (RX_BUFFER_SIZE - 1U)

static volatile char rx_buffer[RX_BUFFER_SIZE];

static volatile uint32_t rx_head = 0U;
static volatile uint32_t rx_tail = 0U;
static volatile uint32_t rx_overflow = 0U;

/* Програмний стан LD2 */
static uint32_t led_state = 0U;

/* ============================================================
 * Передавання одного символу
 * ============================================================ */

static void uart_send_char(char character)
{
    /*
     * TXE = 1 означає, що регістр передавання порожній
     * і готовий прийняти наступний символ.
     */
    while ((USART2_SR & USART_SR_TXE) == 0U)
    {
    }

    USART2_DR = (uint32_t)character;
}

/* ============================================================
 * Передавання рядка
 * ============================================================ */

static void uart_send_string(const char *text)
{
    while (*text != '\0')
    {
        uart_send_char(*text);
        text++;
    }
}

/* ============================================================
 * Перевірка наявності символів у буфері
 * ============================================================ */

static uint32_t uart_rx_available(void)
{
    /*
     * Якщо head і tail не рівні,
     * у буфері є хоча б один непрочитаний символ.
     */
    return (rx_head != rx_tail);
}

/* ============================================================
 * Отримання одного символу з буфера
 * ============================================================ */

static char uart_rx_get_char(void)
{
    char character;

    /*
     * Зчитуємо символ із позиції tail.
     */
    character = rx_buffer[rx_tail];

    /*
     * Переміщуємо tail до наступної позиції.
     * Маска забезпечує перехід із 31 назад до 0.
     */
    rx_tail = (rx_tail + 1U) & RX_BUFFER_MASK;

    return character;
}

/* ============================================================
 * Керування LD2
 * ============================================================ */

static void led_set(uint32_t state)
{
    led_state = state;

    if (led_state != 0U)
    {
        /* Установлення PA5 */
        GPIOA_BSRR = (1U << 5);
    }
    else
    {
        /* Скидання PA5: біт 5 + 16 = 21 */
        GPIOA_BSRR = (1U << 21);
    }
}

/* ============================================================
 * Обробник переривання USART2
 * ============================================================ */

void USART2_IRQHandler(void)
{
    uint32_t next_head;
    char received_character;

    /*
     * Перевіряємо, чи переривання викликане
     * надходженням нового байта.
     */
    if ((USART2_SR & USART_SR_RXNE) != 0U)
    {
        /*
         * Читання DR забирає прийнятий символ
         * та очищає прапорець RXNE.
         */
        received_character = (char)(USART2_DR & 0xFFU);

        /*
         * Обчислення наступної позиції запису.
         * Після позиції 31 відбувається перехід до 0.
         */
        next_head = (rx_head + 1U) & RX_BUFFER_MASK;

        /*
         * Якщо наступна позиція не збігається з tail,
         * у буфері є вільне місце.
         */
        if (next_head != rx_tail)
        {
            rx_buffer[rx_head] = received_character;
            rx_head = next_head;
        }
        else
        {
            /*
             * Буфер заповнений.
             * Новий символ не записується.
             */
            rx_overflow++;
        }
    }
}

/* ============================================================
 * Обробка прийнятої команди
 * ============================================================ */

static void process_command(char command)
{
    switch (command)
    {
        case '1':
            led_set(1U);
            uart_send_string("LD2 ON\r\n");
            break;

        case '0':
            led_set(0U);
            uart_send_string("LD2 OFF\r\n");
            break;

        case 't':
        case 'T':
            led_set(led_state ^ 1U);

            if (led_state != 0U)
            {
                uart_send_string("LD2 ON\r\n");
            }
            else
            {
                uart_send_string("LD2 OFF\r\n");
            }
            break;

        case 's':
        case 'S':
            if (led_state != 0U)
            {
                uart_send_string("State: LD2 ON\r\n");
            }
            else
            {
                uart_send_string("State: LD2 OFF\r\n");
            }
            break;

        case 'h':
        case 'H':
            uart_send_string(
                "\r\nCommands:\r\n"
                "1 - LED ON\r\n"
                "0 - LED OFF\r\n"
                "t - Toggle LED\r\n"
                "s - Show state\r\n"
                "h - Help\r\n"
            );
            break;

        case '\r':
        case '\n':
            /* Enter ігноруємо */
            break;

        default:
            uart_send_string("Unknown command. Press h.\r\n");
            break;
    }
}

/* ============================================================
 * Головна функція
 * ============================================================ */

int main(void)
{
    char command;

    /* --------------------------------------------------------
     * 1. Увімкнення тактування GPIOA та USART2
     * -------------------------------------------------------- */

    RCC_AHB1ENR |= (1U << 0);
    RCC_APB1ENR |= (1U << 17);

    /* --------------------------------------------------------
     * 2. PA5 — цифровий вихід для LD2
     *
     * MODER5 = 01
     * -------------------------------------------------------- */

    GPIOA_MODER &= ~(3U << 10);
    GPIOA_MODER |=  (1U << 10);

    /* Початково LD2 вимкнений */
    led_set(0U);

    /* --------------------------------------------------------
     * 3. PA2 — USART2_TX, PA3 — USART2_RX
     *
     * MODER2 = 10
     * MODER3 = 10
     * -------------------------------------------------------- */

    GPIOA_MODER &= ~((3U << 4) | (3U << 6));
    GPIOA_MODER |=  ((2U << 4) | (2U << 6));

    /* --------------------------------------------------------
     * 4. Альтернативна функція AF7
     *
     * PA2 = USART2_TX
     * PA3 = USART2_RX
     * -------------------------------------------------------- */

    GPIOA_AFRL &= ~((0xFU << 8) | (0xFU << 12));
    GPIOA_AFRL |=  ((7U << 8) | (7U << 12));

    /* --------------------------------------------------------
     * 5. Швидкість 115200 бод за частоти PCLK1 = 16 МГц
     * -------------------------------------------------------- */

    USART2_BRR = 0x008BU;

    /* --------------------------------------------------------
     * 6. Увімкнення передавача, приймача та RXNE interrupt
     *
     * TE     = 1
     * RE     = 1
     * RXNEIE = 1
     * -------------------------------------------------------- */

    USART2_CR1 |= USART_CR1_TE;
    USART2_CR1 |= USART_CR1_RE;
    USART2_CR1 |= USART_CR1_RXNEIE;

    /* --------------------------------------------------------
     * 7. Дозвіл USART2_IRQn у NVIC
     *
     * USART2_IRQn = 38
     * 38 - 32 = 6
     * -------------------------------------------------------- */

    NVIC_ISER1 = (1U << 6);

    /* --------------------------------------------------------
     * 8. Увімкнення USART2
     * -------------------------------------------------------- */

    USART2_CR1 |= USART_CR1_UE;

    uart_send_string("\r\n");
    uart_send_string("STM32 UART ring buffer ready.\r\n");
    uart_send_string("Press h for help.\r\n");

    /* --------------------------------------------------------
     * 9. Головний цикл
     * -------------------------------------------------------- */

    while (1)
    {
        /*
         * Основна програма не очікує символ у блокувальному
         * циклі. Вона лише перевіряє буфер.
         */
        if (uart_rx_available() != 0U)
        {
            command = uart_rx_get_char();
            process_command(command);
        }

        /*
         * Тут надалі можна виконувати інші завдання:
         * опитування датчиків, обчислення, керування PWM тощо.
         */
    }
}
